// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webEcom.Data;

#nullable disable

namespace webEcom.Migrations
{
    [DbContext(typeof(webEcomDBContext))]
    partial class webEcomDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webEcom.Models.ProductDATA", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduct"));

                    b.Property<byte[]>("IformfileProductInputImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("ProductBill")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProductCreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProductPrice")
                        .HasColumnType("real");

                    b.Property<DateTime?>("ProductSendBill")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductSendNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProductSendTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProductSendTimesuccess")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductUserAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProductUserCart")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductUserTel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProduct");

                    b.ToTable("PRODUCT");
                });
#pragma warning restore 612, 618
        }
    }
}
